// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkaZaYbw65RqakCLQjYK63499GAc00pUg',
    appId: '1:3588962029:web:cad4d677aa511b81f2bee4',
    messagingSenderId: '3588962029',
    projectId: 'fir-crudoperation-3010f',
    authDomain: 'fir-crudoperation-3010f.firebaseapp.com',
    storageBucket: 'fir-crudoperation-3010f.appspot.com',
    measurementId: 'G-9ZDNYCTGG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ0j2zadl21jshgbbfREjVoiZv7desBoM',
    appId: '1:3588962029:android:15987c79918adddff2bee4',
    messagingSenderId: '3588962029',
    projectId: 'fir-crudoperation-3010f',
    storageBucket: 'fir-crudoperation-3010f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOybG5MaWsyhGuyd0FKBBRkaUC-DTL3k',
    appId: '1:3588962029:ios:c07a52a2c2432b23f2bee4',
    messagingSenderId: '3588962029',
    projectId: 'fir-crudoperation-3010f',
    storageBucket: 'fir-crudoperation-3010f.appspot.com',
    iosBundleId: 'com.example.firebaseCrudOperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOybG5MaWsyhGuyd0FKBBRkaUC-DTL3k',
    appId: '1:3588962029:ios:8e4e04ed66fe85d5f2bee4',
    messagingSenderId: '3588962029',
    projectId: 'fir-crudoperation-3010f',
    storageBucket: 'fir-crudoperation-3010f.appspot.com',
    iosBundleId: 'com.example.firebaseCrudOperation.RunnerTests',
  );
}
